version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tunevault
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tunevault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - soundstream_net

volumes:
  postgres_data:

networks:
  soundstream_net:
    driver: bridge